services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
  
  backend:
    build: ./backend
    ports:
      - 1000:1000
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend